name: Build Example

on: [push]

jobs:
  checkout-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout2
        uses: actions/checkout@v4

      - name: Setup Node.js enviroment
        uses: actions/setup-node@v4
        with:
          node-version: "15.x"

      - name: Build the code
        run: npm run build

      - name: verification
        run: ls -alhR
