name: Checkout Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List all files in the workspace
        run: ls -alhR
