name: Checkout Example

on: workflow_dispatch

jobs:
  checkout-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: verification
        run: ls -alhR
