name: Build Example

on: [push]

jobs:
  checkout-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js enviroment
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Build the code
        run: |
          npm install
          npm run build

      - name: Test the code
        run: npm test

      - name: Code coverage report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}       # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results
