name: Build Example

on: [push]

jobs:
  checkout-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true

      - name: Setup Node.js enviroment
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Build the code
        run: |
          npm install
          npm run build

      - name: Test the code
        run: npm test

      - name: Code coverage report
        uses: mridang/action-test-reporter@v1.5.0
        with:
          coverage-file: coverage/lcov.info
