name: Build Example

on: [push]

jobs:
  checkout-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js enviroment
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Build the code
        run: |
          npm install
          npm run build

      - name: Test the code
        run: npm test
